---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
    - common

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
    - frontend

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  roles:
    - app


- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true

  roles:
    - db


#- name: deploy apache
#  hosts: apps
#  gather_facts: false
#  become: true
#  hosts: apps
#  tasks:
#  - name: install apache
#    yum:
#      name: httpd
#      state: latest
#  - name: enable apache at boot
#    service:
#      name: httpd
#      enabled: yes
#  - name: start apache
#    service:
#      name: httpd
#      state: started
